server:
  port: 10010 # 网关端口

spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
       routes: # 网关路由配置
       - id: user-service # 路由id，全局唯一
         uri: http://localhost:8123 # 目标服务地址
         predicates: # 断言，路由条件
         - Path=/api/** # 当请求路径满足Path指定的规则时，进行路由

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace


