server:
  port: 10010 # 网关端口

spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
       routes: # 网关路由配置
       - id: user-service # 路由id，全局唯一
         uri: http://localhost:8123 # 目标服务地址
         predicates: # 断言，路由条件
         - Path=/api/** # 当请求路径满足Path指定的规则时，进行路由

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace


dubbo:
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
    # This will enable application-level service discovery only (the recommended service discovery method for Dubbo3).
    # For users upgrading from Dubbo2.x, please set the value to 'all' for smooth migration.
    register-mode: instance
  application:
    qos-enable: true
    name: GcqGatewayApplication
    qos-port: 22222
    qos-accept-foreign-ip: false
    logger: slf4j
  reference:
    interface: com.gcq.gcqcommon.service.UserInterfaceInfoService
    version: 1.0.0
    group: testGroup